# Generated by Django 3.2.15 on 2023-03-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0002_auto_20230309_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
