# Generated by Django 3.2.15 on 2023-03-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_null',
            field=models.CharField(max_length=5, null=True, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(default='null', max_length=100, verbose_name='个性签名'),
        ),
    ]
