# Generated by Django 3.2.15 on 2023-03-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0005_auto_20230310_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=100, null=True, verbose_name='个性签名'),
        ),
    ]
